### ISSUE TITLE
Autocommand not triggered

### ISSUE THREAD

**Issue by lervag** [micangl/cmp-vimtex#1]
The autocommand defined [here](https://github.com/micangl/cmp-vimtex/blob/2e0c79c6c096d0b51222c7d4eae2f2bff7f7bf80/lua/cmp_vimtex/init.lua#L4-L12) is not triggered if cmp-vimtex is loaded lazily by e.g. lazy.nvim. I think this will be a quite common situation.

A simple, but possibly good solution is to add a check if the current file is already a `.tex` file, and to then start the parser immediately.

I would also advice to put all code inside the setup function. That is, `require`ing a script should not have a side effect in itself.

**Comment by micangl** [comment]
@lervag I may have fixed it on branch [test_autocmd](https://github.com/micangl/cmp-vimtex/tree/test_autocmd).

**Comment by lervag** [comment]
No, I don't think so. The `FileType` autocommand will also have triggered before the `.setup()` function is called in my particular case.

**Comment by micangl** [comment]
> A simple, but possibly good solution is to add a check if the current file is already a .tex file, and to then start the parser immediately.

I misunderstood this remark. What did you mean, exactly?

**Comment by lervag** [comment]
I can propose a PR, it might be easier to understand if I show what I mean.

**Comment by micangl** [comment]
I'd appreciate it!

**Comment by lervag** [comment]
See #2, specifically [this commit](https://github.com/micangl/cmp-vimtex/pull/2/commits/ed6bf057eaa68bb63f9c34a9e09fd573755b9f0d).

**Comment by micangl** [comment]
Wow, great job!

I have a doubt, though: wouldn't the parser be triggered two times if `setup` wasn't called by `lazy.nivm`, i.e. inside the `init.lua` or automatically? Since, in this case, both the autocmd and
```lua
if vim.opt_local.filetype:get() == "tex" then
    _start_parser()
end
```
would launch parser.

**Comment by lervag** [comment]
> Wow, great job!

Thanks :)

> I have a doubt, though: wouldn't the parser be triggered two times if `setup` wasn't called by `lazy.nivm`, i.e. inside the `init.lua` or automatically? Since, in this case, both the autocmd and
> 
> ```lua
> if vim.opt_local.filetype:get() == "tex" then
>     _start_parser()
> end
> ```
> 
> would launch parser.

No, I don't think so - and this is the problem I'm trying to solve. If you are _already_ inside a `.tex` file in which the filetype option is set to `"tex"` when you are running the `.setup` function, then the `FileType` trigger was already executed. Thus the autocommand does not have an effect on the current buffer, and so we want to trigger the parser manually.

**Comment by micangl** [comment]
> No, I don't think so - and this is the problem I'm trying to solve. If you are already inside a .tex file in which the filetype option is set to "tex" when you are running the .setup function, then the FileType trigger was already executed. Thus the autocommand does not have an effect on the current buffer, and so we want to trigger the parser manually.

I understood this; what I meant was: suppose that we use a regular plugin manager, which loads plugins on startup. When `setup` is executed, it sets the autocommand and executes `_start_parser`. Since we are at startup the `FileType` event is triggered, which triggers the parser, _again_, with the autocommand.

**Comment by lervag** [comment]
Ah, but that's where `if vim.opt_local.filetype:get() == "tex"` comes in. With a regular plugin manager that loads plugins on startup, the filetype will _not_ be `"tex"`.

**Comment by micangl** [comment]
Very interesting. I'll test and push as soon as I can.
