### ISSUE TITLE
Bug in bibtex parser

### ISSUE THREAD

**Issue by lervag** [micangl/cmp-vimtex#15]
Given the following lua init file e.g. under `~/test/test.lua`:

```lua
local root = vim.fn.fnamemodify("./.lazy", ":p")

for _, name in ipairs({ "config", "data", "state", "cache" }) do
	vim.env[("XDG_%s_HOME"):format(name:upper())] = root .. "/" .. name
end

local lazypath = root .. "/plugins/lazy.nvim"
if not vim.loop.fs_stat(lazypath) then
	vim.fn.system({ "git", "clone", "--filter=blob:none", "https://github.com/folke/lazy.nvim.git", lazypath })
end
vim.opt.runtimepath:prepend(lazypath)

local plugins = {
	"hrsh7th/nvim-cmp",
	"micangl/cmp-vimtex",
	"lervag/vimtex",
}
require("lazy").setup(plugins, { root = root .. "/plugins" })

vim.g.vimtex_cache_root = "."
vim.g.vimtex_cache_persistent = false

vim.cmd([[silent! close]])
vim.cmd.edit("test.tex")
```

And the following `test.tex`:

```tex
\documentclass{article}
\usepackage[backend=biber]{biblatex}
\addbibresource{biblatex-examples.bib}

\begin{document}
Test \cite{gaonkar}
\end{document}
```

We get the following error message:

```
Error executing vim.schedule lua callback: .../test/.lazy/plugins/cmp-vimtex/lua/cmp_vimtex/parser.lua:64: attempt to index local 'entry' (a nil value)
stack traceback:
        .../test/.lazy/plugins/cmp-vimtex/lua/cmp_vimtex/parser.lua:64: in function 'format_entry'
        .../test/.lazy/plugins/cmp-vimtex/lua/cmp_vimtex/parser.lua:143: in function 'callback'
        ...g/test/.lazy/plugins/cmp-vimtex/lua/cmp_vimtex/timer.lua:72: in function <...g/test/.lazy/plugins/cmp-vimtex/lua/cmp_vimtex/timer.lua:66>
```

**Comment by micangl** [comment]
Thanks for raising the issue. Currently I'm in an exam session, so I won't have time to look into this for a while (until the end of february, most likely). I will, then, try to add some of your enhancements to the parser.

Unfortunately, I really have no time at the present moment.

**Comment by lervag** [comment]
No problem, do it when you have the time.

**Comment by benbrastmckie** [comment]
I'm not sure if this is a related issue or not, but I lost the bibtex autocomplete functionality when writing `\citet{...` and the like. I also cannot get the search function mapping `vim.keymap.set("i", "<C-s>", function() require('cmp_vimtex.search').search_menu() end)` to work. Sorry for the redundancy if this is the same issue and conflation of issues if it isn't.

**Comment by micangl** [comment]
I have finally time to look into this. Would you mind posting the `biblatex-examples.bib` file included above?

**Comment by lervag** [comment]
`biblatex-examples.bib` is actually included with biblatex; i.e., you don't need the file, because you already have it. You can verify that with `kpsewhich biblatex-examples.bib`, which should output something like this:

```
> kpsewhich biblatex-examples.bib
/usr/share/texmf-dist/bibtex/bib/biblatex/biblatex/biblatex-examples.bib
```

**Comment by micangl** [comment]
I should have fixed it with the last commit.

The bug was related to the issue I raised for `vimtex` about a month ago: I was overwriting the native `label` and `key` bibtex fields.

**Comment by lervag** [comment]
Great, thanks!
