### ISSUE TITLE
Hide package details, show symbols

### ISSUE THREAD

**Issue by Kayzels** [micangl/cmp-vimtex#25]
Is there any way to hide the details that say which source the command comes from, but keep symbols showing? At the moment, I've disabled menu entirely for cmp-vimtex, because it makes the cmp dropdown a lot larger because of the information showing me which package a command comes from. I tried to disable that using `info_in_menu = false`, and while it hides some information, the source still shows. If I type something like `\forall`, it shows `[cmd: default] ∀`. I'd like to just see the ∀, without it telling me the package.

Would this be achievable at all, or require a significant rewrite or config change?

**Comment by micangl** [comment]
I've added the `origin_in_menu` option.
