### ISSUE TITLE
Change of cwd when opening .tex file

### ISSUE THREAD

**Issue by marcusfschmidt** [micangl/cmp-vimtex#6]
I noticed that upon opening a .tex file in neovim, my cwd would change to the same as that of the file itself. I narrowed this behavior down to this plugin - disabling it leaves my cwd unchanged. It is simply added using lazy and, as per the vimtex documentation, vimtex is added as as cmp source for the .tex filetype. 

I am unsure where this behavior comes from - but I will be happy to help out if it is not immediately reproducible and turns out to be a more complicated interplay between my plugins.

**Comment by micangl** [comment]
Thanks for the warning! I should have fixed the issue with the last commit. Let me know if it works.

**Comment by marcusfschmidt** [comment]
Yep, that did it :)
