### ISSUE TITLE
README instructions not working for me?

### ISSUE THREAD

**Issue by jwbullard** [micangl/cmp-vimtex#7]
Using neovim v0.9.4 on Mac OS Sonoma 14.1.1 with nvim-cmp for autompletion, but when I tried to include cmp-vimtex using your README instructions, none of the functionality seems to be working for LaTeX files.  Here is my nvim-cmp.lua file:

<img width="692" alt="Screenshot 2023-11-30 at 5 15 00 PM" src="https://github.com/micangl/cmp-vimtex/assets/62448796/6be8ba64-ebec-4924-ae2e-8c7bb90be4ab">

And my plugins setup file (uses packer for plugin management):

<img width="821" alt="Screenshot 2023-11-30 at 5 16 31 PM" src="https://github.com/micangl/cmp-vimtex/assets/62448796/4a896f40-3258-4e4a-bebc-3528aa8419bf">

This isn't exactly a bug, it's more likely that I'm missing something in the configuration, but I'll be grateful for any help you might be able to provide!

**Comment by micangl** [comment]
Thanks for raising the issue. I'm thinking that `lspkind` may be interfering with the display of the provided information. What happens if you try to disable it (just commenting out the `format` function should be sufficient)?

**Comment by jwbullard** [comment]
That was absolutely the issue!  Thanks so much.  In fact I don't even seem to need lspkind so I just removed that block.  Thanks again for being so responsive!

**Comment by micangl** [comment]
@jwbullard I've opened a [pull request](https://github.com/onsails/lspkind.nvim/pull/72) to fix the issue directly in `lspkind-nvim`. If it's accepted you'll be able to keep using it and, when I'll find some time, I'll add a warning to the `README.md`, with a possible manual configuration too.

**Comment by micangl** [comment]
@jwbullard The pull request I mentioned has been merged into master. This means that you should be able to use `lspkind.nvim` again, if you want to.

**Comment by jwbullard** [comment]
Thanks for following up!
